server:
  port: 6060
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
   # url: jdbc:mysql://47.113.185.50:3306/data_fusion?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://localhost:3518/data_fusion?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: ldnCS@518       #Rdc@2022

  mvc:
    servlet:
      load-on-startup: 1

  sql:
    init:
      schema-locations: classpath:db/table.sql
      data-locations: classpath:db/init.sql
      mode: always

  kafka:
    bootstrap-servers: localhost:9092 #47.113.185.50:9092
    consumer:
      group-id: topic_data_service_original_message_group
      auto-offset-reset: latest

mybatis:
  mapper-locations: classpath:/fusion/*.xml, classpath:/decision/*.xml, classpath:/access/*.xml